name: flutter_chat_demo
description: This is the demo for chat app by Flutter
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.14.0
  fluttertoast: ^8.2.5
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.1
  photo_view: ^0.14.0
  provider: ^6.1.2
  intl: ^0.19.0
  # provider: ^6.0.1
  # intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=2.19.2 <3.0.0"